services:
  db:
    image: postgres:15
    container_name: django_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres          
      POSTGRES_PASSWORD: compra123  
      POSTGRES_DB: compraAhorra        
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
