# Generated by Django 5.1.2 on 2024-11-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0002_administrador_mediopago_respaldo_tipoproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='administrador',
        ),
    ]
