# Generated by Django 5.1.2 on 2024-12-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0002_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
