# Generated by Django 5.1.2 on 2024-12-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0003_detallecompra_direccion_detallecompra_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='email',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='telefono',
        ),
    ]
